### ISSUE TITLE
Checklist for v1.0.0-alpha-2

### ISSUE THREAD

**Issue by djsiddz2** [sushantkumar23/azuro-css#5]
Creating a short checklist for alpha2 release which should be bower-ready.

- [ ] Add Sections default SCSS
- [ ] Focus, Hover and Active state specific rules for inputs and buttons
- [ ] Add new .background-$color utility classes
- [ ] Fix footer spacing
- [x] Update bower.json
- [ ] Update docs to reflect how to install this package in any project using Bower
